- lib/terminal.js
- package.json
- plugins/addons/index.js
New command - addons:plans:info - shows info about a given service plan
Fixed formatting of 'attached_to' property in the addons:info command
COBRA-1820
> Show info about service plans

- README.md
- aka.js
- lib/terminal.js
- package.json
If the check for updates option is enabled (via aka auth:profile), the cli will asynchronously check for updates upon running a command if it's been at least AKA_UPDATE_INTERVAL (default 24hr) since the last check. The async command will save the result of the check in the ~/.akkeris/ directory as AKA_UPDATE_FILENAME (default .aka_version), and will be used when providing the usage statement to output the current version and the latest available version.
> Automatic NPM Version Checking

- README.md
- aka.js
- lib/terminal.js
- package-lock.json
- package.json
- plugins/builds/index.js
- plugins/maintenance/index.js
- Default command (i.e. `aka` with no command) will take you to the new `help` command.
- You can choose to use the old Akkeris help by setting `AKKERIS_HELP_OLD` to `true` or `1`, or by choosing `y` when prompted during profile setup
- You can also use the `-a` flag to show the old help (`aka help -a`)
- Commands are organized into groups (their plugin folder) and using `aka help [group]` will show all the commands in that group
- Help for individual commands can be shown by `aka help [group] [command]` or `aka [command] --help`
> Improve CLI Help

- aka.js
If a plugin has `update.js` in its root directory, when `aka update` is used, this file will be required instead of using the `update` function in the plugin `index.js`.
This gives plugins the ability to run a `npm install` to update dependencies while not tying us too closely to NPM.
> provide ability to use update.js to update plugins

- aka.js
- package.json
Fixes the following:
- Adds the `plugins` command group to help
- Adds "meta" commands to help
- `auth:profile`
- `autocomplete`
- `update`
- `version`
> add meta cmds (update, version) and plugins group

- aka.js
- package.json
The line of code with `.alias('a', 'all')` meant that `-a` and `-all` were aliases for each other on every command on the project - i.e. if a command had an option for `-all` AND and option for `-a` (as in `aka releases`) they would clash.
I'm pretty sure I thought that `.alias()` applied for the previous `.command()` call ... brain fart
> fix help option alias

- README.md
- aka.js
- lib/plugins.js
- package-lock.json
- package.json
- plugins/apps/index.js
- plugins/audits/index.js
- plugins/metrics/index.js
- Use `cross-spawn` package for spawning child processes
- Use `path.basename(__filename)` instead of `argv["$0"]` for script name
- Improve temporary folder deletion
- Provide `cross-spawn` as a parameter to `install.js` during plugin installation
- This lets plugins use `cross-spawn` during installation for things like `npm install`
> cross platform improvements

- lib/terminal.js
- plugins/addons/index.js
- plugins/apps/index.js
Remove addon display from `apps:info` as it was getting cluttered - added message to use `addons -a appname` instead
Added `attached from` to the addon info page for apps
Also added a helper jsdoc so I could remember which characters create which colors on `appkit.terminal.markdown`
> tweak apps:info, add 'attached from' to addons

- package.json
- plugins/apps/index.js
ignore 404 response to `/apps/app-space/pipeline-couplings`
... d'oh
> Fix for apps:info crash if app is not in a pipeline

- lib/terminal.js
- package-lock.json
- package.json
- plugins/hooks/index.js
- Change dependency on the deprecated `cli-table` to `cli-table3` which has more features and is actively maintained (gets regular security updates) while still being backwards-compatible with `cli-table`
- Add `aka hooks:fetch` which gets a list of available hook events & descriptions from the controller
> aka hooks:fetch - Dynamically get hook events from controller

- aka.js
- package-lock.json
- package.json
**Fix subcommand help**
- Issue: `aka help apps apps:info` would display the help for `aka help`
- Cause: Yargs now caches the "help" output for some reason... so if you call `parse` twice, the second time it will display the (incorrect) cached help.
- Fix: They pushed a fix for this, but for some reason, something that I'm doing is not triggering their call to clear the cache. So instead I'm clearing it manually
**Improve help commands**
- Issue: `aka help apps info` fails with message "Invalid command: info`
- Cause: The code expects the full command name (including command group prefix) as the second argument
- Fix: Updated code to allow either full command name or partial name
I've also cleaned up the code a bit to remove things like `--version` option on every command
> improve help commands

- lib/plugins.js
- package-lock.json
- package.json
Not sure why I tried to compare the node version as a string, that was a brain fart.
Added NPM's "semver" package as a dependency, which is already required by a number of our dependencies anyway. Tested installing plugins with node 8 and it worked fine
> use semver package instead of string comparison

- lib/terminal.js
- package.json
- plugins/features/index.js
PATCH `/apps/${args.app}/features/${args.FEATURE}` already restarts the app. Also the `RESTART` env var is deprecated.
Minor fix to the `loading` display function
> don't set RESTART var to restart dyno, + bug fix

- lib/plugins.js
- package.json
When installing plugins, capture `stderr` and look for either "authentication failed" or "enabled SAML SSO". Then, let the user know what happened (and provide the validation URL if available)
> improve plugin installation error messages

- package.json
- plugins/apps/index.js
- Wrap assert calls with a try catch block for a better user experience
- Fix `oneclick_app_option` messing up the `blueprint_app_option` object
> assert handling, fix blueprint options

- aka.js
- package.json
- Handle getting help for specific commands a bit cleaner
- When a user runs `aka version`, it should only return installed 3rd party plugins.
> fix bug with help command, version command

- aka.js
- package.json
Help messages will now use the alias name (aka/ak) instead of the filename (aka.js)
> use process.argv[1] instead of __filename

- .dockerignore
- .github/workflows/merge_docker.yml
- .github/workflows/release_docker.yml
- .gitignore
- Dockerfile
- README.md
This should let people who are having trouble installing the CLI for whatever reason (e.g. Windows users?) use a Docker image instead. I've also added two Actions that should push new images to DockerHub on a new release tag as well as a new push to master.
> Add Docker Image

- package.json
Bump to 3.1.21 to prepare for releasing the beta recommendations-api commands
> Bump package version in preperation for release

- package.json
- plugins/maintenance/index.js
Add ability to scale/backup/restore formations that match either a filter or a suffix/prefix.
This is especially useful for people with apps that have large amounts of formations that follow a pattern (e.g. test engineers at OCT)
> add prefix/suffix/filter options for maintenance

- plugins/repo/index.js
Adds a new command that you can use to tell Akkeris to do a fresh build from the configured Github source.
`aka repo:build`
Depends on https://github.com/akkeris/controller-api/pull/328/files
> add aka repo:build command

- aka.js
- package-lock.json
I noticed that `ak version` doesn't print out the versions of the plugins, which would be handy for making sure users are using updated versions of plugins when troubleshooting issues.
I noticed that if the plugin had a root level key of `version`, it'd just print out `@${group}` which looks funny, for example:
`pg @pg` instead of something like `pg @1.2.3` or `pg v1.2.3`.
Here's a sample of it working should all plugins have versions (I stubbed them in for this example).
```sh
$ npm run aka version
> akkeris@3.1.26 aka
> node -r dotenv/config aka.js "version"
akkeris/3.1.26 x64-darwin node-v14.18.0
=== Installed Plugins
compare v1.0.0
fire v1.2.3
gitflow v1.1.0
java v2.3.1
kafka v5.4.0
memcached v1.0.3
pg v19.2.1
redis v1.3.1
starter v0.0.1
taas v1.0.0
```
One thing that might make it …
> Add version support for plugins

- plugins/filters/index.js
We noticed we cannot create `csp` filters using the Akkeris CLI due to the input validation.
> bug: add csp as a valid filter type
